"""Persists dragged placements to a dedicated, GUI-owned config file.

Deliberately never touches hyprland.conf. `plugin =` doesn't expand `~` and a
tool that also hand-edits a file full of the user's own comments and structure
is a tool that will eventually mangle both. Instead this owns one small file
completely and the user sources it once:

    source = ~/.config/hypr/mmcursor-layout.conf

Only monitors the user actually dragged this session are written; anything
already in the file for a monitor that wasn't touched is preserved verbatim,
so multiple save sessions accumulate instead of clobbering each other, and
monitors left on derived/relational placement stay that way — dragging one
monitor should not silently freeze every other monitor's placement too.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

DEFAULT_PATH = Path.home() / ".config" / "hypr" / "mmcursor-layout.conf"

_HEADER = (
    "# Generated by mmcursor-gui.\n"
    "# Hand edits survive a save EXCEPT for mmcursor-place lines, which are\n"
    "# rewritten wholesale from what the GUI last knew about each monitor it\n"
    "# was told to move. Source this file from hyprland.conf:\n"
    "#\n"
    "#   source = {path}\n"
    "#\n"
    "# and reload (or run mmcursor-gui's \"Apply & Reload\") to pick it up.\n"
)

_PLACE_RE = re.compile(r"^\s*mmcursor-place\s*=\s*([^,]+),")


def _existing_placements(path: Path) -> dict[str, str]:
    """name -> the full `mmcursor-place = ...` line text (no trailing newline)."""
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        m = _PLACE_RE.match(line)
        if m:
            out[m.group(1).strip()] = line.strip()
    return out


def save_placements(moved: dict[str, tuple[float, float]], path: Path = DEFAULT_PATH) -> Path:
    """moved: {monitor_name: (x_mm, y_mm)} for monitors dragged this session."""
    lines = _existing_placements(path)
    for name, (x, y) in moved.items():
        lines[name] = f"mmcursor-place = {name}, at, {x:.2f}, {y:.2f}"

    path.parent.mkdir(parents=True, exist_ok=True)
    body = _HEADER.format(path=path) + "\nplugin {\n    mmcursor {\n"
    for name in sorted(lines):
        body += f"        {lines[name]}\n"
    body += "    }\n}\n"

    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(body)
    os.replace(tmp, path)
    return path


def is_sourced_from(hyprland_conf: Path, layout_path: Path = DEFAULT_PATH) -> bool:
    """Best-effort check so the GUI can nudge the user if they saved but never
    wired the `source =` line in — the classic way this kind of tool's output
    silently does nothing."""
    if not hyprland_conf.exists():
        return False
    target = str(layout_path)
    for line in hyprland_conf.read_text().splitlines():
        s = line.strip()
        if s.startswith("source") and target in s:
            return True
    return False
